### ISSUE TITLE
How to set the text height in table

### ISSUE THREAD

**Issue by www741147** [aspose-words/Aspose.Words-for-.NET#272]
source:[222.docx](https://github.com/aspose-words/Aspose.Words-for-.NET/files/3976458/222.docx)
copied file:[saved.docx](https://github.com/aspose-words/Aspose.Words-for-.NET/files/3976460/saved.docx)

Code:
![image](https://user-images.githubusercontent.com/6457259/71052422-3bc01600-2186-11ea-9f02-2889a944d665.png)

I found the text in table have some margin bottom px.
![image](https://user-images.githubusercontent.com/6457259/71052474-627e4c80-2186-11ea-945c-360584eac169.png)
How can I do to remove the distance.

Any suggestion?

**Comment by AlexNosk** [comment]
@www741147 Thank you for reporting this problem to us. I managed to reproduce it and logged the problem in our bug tracking system as issue **WORDSNET-19715**. We will let you know once it is resolved.
The actual reason of the problem is that in your document document defaults for paragraph are not specified. After open/save Aspose.Words adds these defaults where paragraph spacing after is 10pt. But MS Word uses 8pt as default paragraph spacing after. As a temporary workaround, you can explicitly specify default paragraph spacing after using the following code:
           
```
Document doc = new Document(@"C:\Temp\in.docx");
doc.Styles.DefaultParagraphFormat.SpaceAfter = 8;
doc.Save(@"C:\Temp\out1.docx");
```
Hope this helps.

**Comment by www741147** [comment]
ok.
let me try it.

**Comment by www741147** [comment]
doc.Styles.DefaultParagraphFormat.SpaceAfter = 0;
solved it.
thx.
