### ISSUE TITLE
在ApiExamples的Data里Reporting engine template - Chart series color.docx这个文档里面柱状图上的颜色是怎么代码实现的

### ISSUE THREAD

**Issue by cqinglive** [aspose-words/Aspose.Words-for-.NET#287]
like the title,

**Comment by AlexNosk** [comment]
@cqinglive You can simply change the color in the template. For example you can select chart style. Unfortunatly there is no way to change series color programmatically yet. This feature is logged as **WORDSNET-12640**. We will let you know once this feature is available.

**Comment by cqinglive** [comment]
> @cqinglive You can simply change the color in the template. For example you can select chart style. Unfortunatly there is no way to change series color programmatically yet. This feature is logged as **WORDSNET-12640**. We will let you know once this feature is available.

Ok,thanks

**Comment by AlexNosk** [comment]
@cqinglive  The issues you have found earlier (filed as WORDSNET-17769) have been fixed in this Aspose.Words for .NET 21.6. Please see the release notes for the code example:
https://docs.aspose.com/words/net/aspose-words-for-net-21-6-release-notes/#implemented-ability-to-set-fill-and-stroke-formatting-for-chart-series-data-points-and-markers
