### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [aspose-words/Aspose.Words-for-.NET#301]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by awaishafeez** [comment]
@huntr-helper
Please post this query in our [free support forums](https://forum.aspose.com/) so that our team can help you properly and timely. Thanks.

**Comment by JamieSlome** [comment]
@awaishafeez - is there any way to provide the details via e-mail?

**Comment by awaishafeez** [comment]
@JamieSlome
I am afraid, the main avenue of technical support is through our [free support forums](https://forum.aspose.com/) only. However, when you provide details via forum post, please make sure to tick-mark the "Private Topic" checkbox so that only you and Aspose staff members can see its content.
